#
name: Lint Markdown

on:
  pull_request:
    branches: [master]
    paths:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies and lint markdown
        run: |
          cd docs
          npm ci
          npm run lint-md
